export const JEFF_QUESTIONS = [
  { id: 1, text: "What is the greatest claim to fame of anyone in your family history?", hint: null },
  { id: 2, text: "Fill in the blank: I make my bed ______ times a week.", hint: null },
  { id: 3, text: "If my significant other were a superhero, he/she would be ___________.", hint: "Ant-Man, Aquaman, Batman, Captain America, Captain Marvel, Catwoman, Green Lantern, Incredible Hulk, Iron Man, Robin, Spider-Man, Supergirl, Superman, Wonder Woman... If no significant other, answer for a friend or family member." },
  { id: 4, text: "Would you rather be a plumber or an electrician?", hint: null },
  { id: 5, text: "Would you rather continue your sleeping habits right now or never have to sleep again (with no ill effects)?", hint: null },
  { id: 6, text: "If you had to add one hour a day to your TV watching, would you choose: the movie channel, CNN, ESPN, or the comedy channel?", hint: null },
  { id: 7, text: "What if you were only allowed to watch one hour of TV total — which of those would it be?", hint: null },
  { id: 8, text: "Did O.J. do it?", hint: null },
  { id: 9, text: "Would you rather eat 6 raw eggs or 1 tennis ball-sized raw onion in 5 minutes?", hint: "Would your answer change if you had to do this every day for a month?" },
  { id: 10, text: "Would you rather spend 10 hours on a plane in first class (destination is your starting point) or 10 hours in your kitchen without being allowed to leave?", hint: "If you need to use the bathroom during the kitchen option, you'd have to do so in the kitchen." },
  { id: 11, text: "Where were you when you learned what happened on 9/11? Do you know anyone who perished?", hint: null },
  { id: 12, text: "If you were a car, what kind of car do you think other people would expect you to be?", hint: "This is about personality. If it takes you ten minutes to order dinner, no one thinks you're a Ferrari." },
  { id: 13, text: "If you were given $100,000 that HAD to be spent on either a speedboat or sailboat — which would it be?", hint: null },
  { id: 14, text: "If you could live to be 75 in perfect health and then pass away on your 75th birthday, or accept whatever God's current plan may be — which would you choose?", hint: "You may want to adjust the age depending on your audience." },
  { id: 15, text: "On a Saturday, would you rather do 8 hours of yard work or 8 hours of house cleaning?", hint: "It's 90 degrees outside. What if it were 45 degrees?" },
  { id: 16, text: "What is the most expensive meal you have ever had?", hint: null },
  { id: 17, text: "How many times do you use a towel before you wash it?", hint: null },
  { id: 18, text: "Finish this sentence: The one appliance in my house I would replace if it were free is ___________.", hint: "You get $5,000 to use. If you only spend $1,000, you keep the rest." },
  { id: 19, text: "Would you rather your child grow up to be a controversial and famous rock star, or a good and dependable nurse?", hint: null },
  { id: 20, text: "What is the weirdest tradition of your significant other's family?", hint: "If no significant other, answer for a friend or family member." },
  { id: 21, text: "What is currently the biggest sibling squabble among your siblings?", hint: "If an only child, answer for your broader family — parents, cousins, etc." },
  { id: 22, text: "What are three words that best describe your mom or dad?", hint: null },
  { id: 23, text: "If the Presidency was chosen by lottery and you knew you would get the winning ticket — would you go get it?", hint: "Six-year term, cannot be re-elected, you'd have to move to Washington DC, everything else about the Presidency applies." },
  { id: 24, text: "Same question as above but for a Senate seat.", hint: null },
  { id: 25, text: "Is there anything you would never, ever, ever tell your mom or dad?", hint: null },
  { id: 26, text: "Finish this sentence: My mom/dad would weep if they knew I had _______.", hint: "Perhaps skip if your mom or dad is present... or finish it with 'always loved them more than life itself.'" },
  { id: 27, text: "Where is your favorite place to shop?", hint: null },
  { id: 28, text: "Do you prefer sun or shade?", hint: null },
  { id: 29, text: "What is your favorite indoor temperature? Outdoor temperature?", hint: null },
  { id: 30, text: "Do you know anyone who died in war?", hint: null },
  { id: 31, text: "Who will look better in 10 years — you or your significant other?", hint: null },
  { id: 32, text: "Would you rather jump off a 60-foot cliff into deep water, or bungee jump 200 feet over a cornfield?", hint: null },
  { id: 33, text: "Would you rather run naked for 15 minutes in your front yard at noon on Saturday, or get a crew cut?", hint: "What if it was your backyard? Men would have to shave their heads." },
  { id: 34, text: "Finish this sentence: The weirdest thing about my significant other's family is ___________.", hint: null },
  { id: 35, text: "Would you rather spend $500 in a grocery store, a sporting goods store, or a clothing store?", hint: null },
  { id: 36, text: "Finish this sentence: If I were given $100,000 to renovate my house, I would use it for ___________.", hint: "Could be a room, landscaping, basement, addition, etc." },
  { id: 37, text: "How many TVs are in your house?", hint: null },
  { id: 38, text: "What foreign languages do you speak?", hint: "Did you ever live somewhere where that was the language?" },
  { id: 39, text: "How many CDs do you own? DVDs?", hint: null },
  { id: 40, text: "Would you rather eat 10 hot dogs in one day, or not eat a single hot dog for 10 years?", hint: "If you eat the 10, you can eat hot dogs whenever you want for the next 10 years. Otherwise, no dogs for you." },
  { id: 41, text: "Finish this sentence: My significant other is better than anyone I know at ___________.", hint: "Consider throwing in a 'let's keep it PG-13.'" },
  { id: 42, text: "How much would someone have to offer you to buy your house if they knocked on your door today and you had to move within 72 hours?", hint: "How about if they gave you two weeks?" },
  { id: 43, text: "Complete this sentence: Although they maybe wouldn't admit it, I think my parent's dream for me may have been ___________.", hint: null },
  { id: 44, text: "Answer this sentence: Although I may not tell them this, my dream for my child is ___________.", hint: "Name which child if you have more than one." },
  { id: 45, text: "What is the weirdest thing you have ever been paid for?", hint: null },
  { id: 46, text: "If you had to spend $5,000 on improving your home and it could only be painting or carpet — which is it?", hint: null },
  { id: 47, text: "How much would I have to pay you right now for your computer? You would not be allowed to back anything up.", hint: "Whatever is on it will be wiped before being sold." },
  { id: 48, text: "What is the most valuable thing you have ever lost or that has been stolen?", hint: null },
  { id: 49, text: "For one month you get one of the following — which do you choose: a personal chef (one meal for your home 3x a week), a housecleaner (4 hours 3x a week), or a massage therapist (two 60-minute massages a week)?", hint: "None are transferable to people outside your home." },
  { id: 50, text: "What is the one bill that makes you cringe when you see it?", hint: null },
  { id: 51, text: "How much time do you spend reading the news each week?", hint: null },
  { id: 52, text: "What is your favorite TV series currently? Of all time?", hint: null },
  { id: 53, text: "Finish this sentence: My significant other would say that I am better than anyone she/he knows at ___________.", hint: null },
  { id: 54, text: "Your friends say — 'the weirdest thing about you is _________.'", hint: null },
  { id: 55, text: "The one thing in my house that I have organized is ___________.", hint: null },
  { id: 56, text: "Finish this sentence: If I had to leave for a formal dinner party starting at 7:00 pm (30 minutes away), I would begin getting ready at ___________.", hint: null },
  { id: 57, text: "How much do you spend a year on hair care — coloring, shampoo, haircuts?", hint: null },
  { id: 58, text: "What is the greatest contribution to society from anyone in your family history?", hint: null },
  { id: 59, text: "If you had to spend 3 hours a day for the next 3 months doing one of the following, which would it be: learning a foreign language, working out, doing volunteer work, or watching the history channel?", hint: null },
  { id: 60, text: "How much time do you spend cleaning the house a week?", hint: "Includes dishes but not laundry." },
  { id: 61, text: "How many books do you read a year? Fiction or non-fiction?", hint: null },
  { id: 62, text: "How many pages of text do you type a year — including everything, email, etc.?", hint: "One page = 30 lines single spaced." },
  { id: 63, text: "How long is your average shower?", hint: null },
  { id: 64, text: "Have you ever been on a blind date?", hint: null },
  { id: 65, text: "If you were a professional athlete, what sport? (You'd get paid the same no matter what.)", hint: null },
  { id: 66, text: "One thing I do not need to buy for a long time is ___________.", hint: null },
  { id: 67, text: "If you were in the Olympics, what event?", hint: null },
  { id: 68, text: "If you could go back in time and give your younger self advice, what would it be?", hint: "Take your age and cut it in half. What would you tell that version of yourself?" },
  { id: 69, text: "Would you rather be a professional athlete (a starter, but not a superstar) or win a gold medal in the Olympics?", hint: null },
  { id: 70, text: "What would you like your ideal commute to be? What is your preferred mode of transportation?", hint: null },
  { id: 71, text: "What is the dumbest thing you have ever said?", hint: null },
  { id: 72, text: "Do you support the death penalty?", hint: "Heads up: if you are with opinionated people, this could become the last question of the evening." },
  { id: 73, text: "If you have traveled frequently: 'I hate to generalize, but I have traveled a lot and one thing I have found about ___________ is ___________.'" , hint: null },
  { id: 74, text: "Fill in the blanks: 'I hate to generalize, but I have traveled a lot and one thing I have found about ___________ is ___________.'" , hint: null },
  { id: 75, text: "Finish this sentence: I wish I could change _______ about my significant other.", hint: "Be very careful." },
  { id: 76, text: "Finish this sentence: On average, I eat out ______ times a week.", hint: null },
  { id: 77, text: "Have you ever had a recurring dream? What is it?", hint: null },
  { id: 78, text: "What is your favorite meal: breakfast, lunch, or dinner?", hint: null },
  { id: 79, text: "Finish this sentence: My worst habit is ___________.", hint: null },
  { id: 80, text: "English or Math?", hint: null },
  { id: 81, text: "What was your first fight with your spouse?", hint: null },
  { id: 82, text: "Your significant other will say your worst habit is ___________.", hint: null },
  { id: 83, text: "How many jobs have you had since college? What was your shortest tenure?", hint: null },
  { id: 84, text: "If it cost you $10 an hour to watch TV, how much would you watch compared to now?", hint: "What about $20 an hour?" },
  { id: 85, text: "How much would you have to be offered to immediately give up your entire wardrobe?", hint: "You can keep one item. Everything else — shoes, t-shirts, everything — is included. Sportswear like golf shoes and skis are exempt." },
  { id: 86, text: "How many times a week is each of the following done in your home — and are you the one who does it: garbage emptied, dishwasher emptied, laundry?", hint: null },
  { id: 87, text: "How many places have you lived in your life (where you stayed more than one month)?", hint: null },
  { id: 88, text: "The thing you most like about your physical self is?", hint: null },
  { id: 89, text: "Is there anyone who you feel imitates you — what you do, what you wear, places you go on vacation, etc.?", hint: null },
  { id: 90, text: "If we went into your closet and pulled out every piece of clothing you haven't worn in the past 12 months, how many pieces would we have? What percentage of your wardrobe is that?", hint: null },
  { id: 91, text: "If there is one thing about your physical self you could change, what would it be?", hint: null },
  { id: 92, text: "Complete this sentence: If I had to get a tattoo (or another one) I would get a _______ on my _______.", hint: "Consider lying." },
  { id: 93, text: "What is the largest number of people you have ever spoken in front of?", hint: null },
  { id: 94, text: "Approximately how many countries have you visited (at least one night)? How many have you lived in?", hint: null },
  { id: 95, text: "If you had to live in a different state than the one you're in now, where would you go?", hint: null },
  { id: 96, text: "Would you rather have 3 dogs and 1 hamster, or 6 hamsters, 1 cat, and 1 dog?", hint: "Assume the cat and dog get along... but the hamsters fight." },
  { id: 97, text: "Do you prefer Coke or Pepsi?", hint: null },
  { id: 98, text: "What is the hardest thing you have ever done?", hint: null },
  { id: 99, text: "What is the longest time you have gone without showering? Why?", hint: null },
  { id: 100, text: "How many pillows do you sleep with?", hint: null },
  { id: 101, text: "On average, how long does it take you to fall asleep?", hint: null },
  { id: 102, text: "On average, how many times a year do you go to a doctor? A dentist?", hint: null },
  { id: 103, text: "How many miles do you drive a year?", hint: null },
  { id: 104, text: "Do you have a most prized possession?", hint: null },
  { id: 105, text: "How many times a month do you weigh yourself?", hint: null },
  { id: 106, text: "How fast can you type (words per minute)?", hint: null },
  { id: 107, text: "The biggest misconception about me is ___________.", hint: null },
  { id: 108, text: "What was your favorite subject in school (K-8)? In high school?", hint: null },
  { id: 109, text: "What is one aspiration or goal by age 40? 50? Before you die?", hint: null },
  { id: 110, text: "Which have you owned more of in your life — wallets or purses?", hint: null },
  { id: 111, text: "How many phone numbers do you have memorized?", hint: null },
  { id: 112, text: "What is the last major purchase that you regret?", hint: null },
  { id: 113, text: "Who is your favorite dwarf from Snow White and the Seven Dwarfs? Can you name all 7?", hint: null },
  { id: 114, text: "As a child, did you go away to camp? Have you been to a camp as an adult?", hint: null },
  { id: 115, text: "What is your preferred brand of toothpaste?", hint: null },
  { id: 116, text: "Describe your first date.", hint: null },
  { id: 117, text: "When was your first kiss with your significant other?", hint: "Be sure you have this one right, or excuse yourself until your turn has passed." },
  { id: 119, text: "The one person you regret having not asked out was?", hint: null },
  { id: 120, text: "Describe your worst date.", hint: null },
  { id: 121, text: "Finish this sentence: Taxes in this country are ___________.", hint: "If you are with controversial people, skip this one." },
  { id: 122, text: "If you could only have 2 things stranded on a desert island, what would they be?", hint: null },
  { id: 123, text: "Of all the people you know, who would best survive if dropped on a deserted island?", hint: null },
  { id: 124, text: "Who is the oldest living person you know?", hint: null },
  { id: 125, text: "Do you think it is harder to become a doctor or a lawyer?", hint: null },
  { id: 126, text: "What profession do you think should require more training, or should be harder to get a license or degree for?", hint: null },
  { id: 127, text: "Do you think man has been on the moon?", hint: null },
  { id: 128, text: "Name 2 pet peeves of your spouse. (Not necessarily about you.)", hint: null },
  { id: 129, text: "How many magazines do you subscribe to?", hint: null },
  { id: 130, text: "If you had to live in a foreign country for 5 years, which would you choose? You cannot leave the entire time.", hint: "Your job, housing, and schooling would all be equivalent to your current situation." },
  { id: 131, text: "Did Michael Jackson do it? (Define 'it' however you wish.)", hint: null },
  { id: 132, text: "Finish this sentence: The one occupation that is just underpaid in this country is ___________.", hint: null },
  { id: 133, text: "Can you name every state that begins with the letters A, M, or T?", hint: null },
  { id: 134, text: "What was the last thing you read or heard in the news that upset you?", hint: null },
  { id: 135, text: "Who is the most famous person you've ever had a relationship with?", hint: null },
  { id: 136, text: "Do you know anyone who has committed a major crime and gotten away with it?", hint: null },
  { id: 137, text: "Do you know anyone currently serving time? Have you ever spent a night in jail?", hint: null },
  { id: 138, text: "Do you know anyone who is doing exactly what they want to do with their life? Do you want to kill that person?", hint: null },
  { id: 139, text: "How many people did you know who passed away before age 20? Before 40?", hint: null },
  { id: 140, text: "Who is the most famous or successful person who graduated from your high school class?", hint: "Did you think they'd be that successful? Do you wish they got a tax audit?" },
  { id: 141, text: "Do you consider yourself a jealous person?", hint: null },
  { id: 142, text: "Who is the most annoying person you know and why?", hint: "First name only is fine. If you're having dinner with that person, use an alias." },
  { id: 143, text: "Is there anyone with whom you are not on speaking terms?", hint: "Always a bad question if the person's answer is in the room." },
  { id: 144, text: "Is there anyone whom you used to speak with every day (for at least a year) who you haven't spoken with in several years?", hint: "I thought so." },
  { id: 145, text: "Do you know anyone who had a near-death experience?", hint: null },
  { id: 146, text: "What is the closest to death you have ever been?", hint: null },
  { id: 147, text: "If you could change one law, what would it be? Would your answer change if it became publicly known?", hint: null },
  { id: 148, text: "How many countries have you been to?", hint: null },
  { id: 149, text: "How many countries do you think there are in the world?", hint: "The answer is 195." },
  { id: 150, text: "If you could only eat one meal for a month (as much and as often as you wanted), what would it be?", hint: "If you say something with variety, be specific — not just 'pizza,' but which kind." },
  { id: 151, text: "What is the approximate number of stitches you have had in your life?", hint: null },
  { id: 152, text: "Who is on the ten-dollar bill?", hint: null },
  { id: 153, text: "What is something you have memorized that most people don't?", hint: null },
  { id: 154, text: "What is the name of your 3rd-grade teacher? What were they like?", hint: null },
  { id: 155, text: "What is your first memory?", hint: null },
  { id: 156, text: "What is the first time you remember your parents being proud of you?", hint: "If this still has not occurred, you may want to write Dear Abby." },
  { id: 157, text: "When was the last time you had aspirin for a headache or another ache?", hint: null },
  { id: 158, text: "When was the last time you did NOT take aspirin for a headache? Has the aspirin talk made you realize you need one now?", hint: null },
  { id: 159, text: "For what reason were you grounded for the first time?", hint: null },
  { id: 160, text: "What is the most pain you have ever been in?", hint: null },
  { id: 161, text: "What is the biggest fear you have for your children, or for children in general?", hint: null },
  { id: 162, text: "How many operations have you had?", hint: null },
  { id: 163, text: "Have you ever met a President? Was he the acting President when you met him?", hint: null },
  { id: 164, text: "Who was President when you were born?", hint: null },
  { id: 165, text: "Have you ever had fire damage to your property?", hint: null },
  { id: 166, text: "If you had to do one of the below for 6 months with no vacation, which would you choose: Cruise Director (4 days/week, 12-hour days, at sea with a 3-day port stop every 6 weeks), Flight Attendant (4-day international trips every 10 days), or Local Train Operator (6 days/week, 8 hours/day)?", hint: null },
  { id: 167, text: "Have you ever been mugged?", hint: null },
  { id: 168, text: "Women: How many times have you been formally proposed to? Men: How many times have you formally proposed?", hint: "This can be a touchy subject, so tread carefully." },
  { id: 169, text: "How many addresses have you had in your life (places where you lived more than 2 months)?", hint: null },
  { id: 170, text: "A neighbor asks you to watch their dog. You never hear from them and they return a year later wanting the dog back. Do you give it back?", hint: "You and your family have grown very fond of the dog." },
  { id: 171, text: "What is the biggest tip you have ever given anyone?", hint: null },
  { id: 172, text: "Have you ever been in a feud with a neighbor?", hint: null },
  { id: 173, text: "Can you remember your last home phone number?", hint: null },
  { id: 174, text: "What is the greatest favor or act of kindness you have ever done for someone?", hint: "It needs to be specific." },
  { id: 175, text: "Do you have a favorite cartoon? What is it?", hint: null },
  { id: 176, text: "What is your most memorable family vacation?", hint: null },
  { id: 177, text: "What family traditions do you currently plan to continue or discontinue?", hint: null },
  { id: 178, text: "What is your favorite dessert?", hint: null },
  { id: 179, text: "Have you ever published anything?", hint: null },
  { id: 180, text: "What was your most difficult class in high school?", hint: null },
  { id: 181, text: "How many F's did you get in college? How many D's?", hint: null },
  { id: 182, text: "Did you ever cheat on a test? Did you ever get caught?", hint: null },
  { id: 183, text: "Have you ever changed a car tire? Would you know how?", hint: null },
  { id: 184, text: "Which of the following can you NOT confidently do: ride a horse, sail, knit or sew, tie a bow tie, drive a motorcycle, drive a stick shift, or rollerblade?", hint: null },
  { id: 185, text: "How many watches do you own? How many are currently working? How many do you actively wear?", hint: null },
  { id: 186, text: "If you could only drink one type of drink for a month (in addition to water), what would it be?", hint: "Be specific — if wine, what kind?" },
  { id: 187, text: "How many car accidents have you been in?", hint: null },
  { id: 188, text: "When were you in the best shape of your life? What could you do that makes you believe that was your peak?", hint: null },
  { id: 189, text: "Did you have a car when you were 16? Who bought it?", hint: null },
  { id: 190, text: "How many cars have you had in your life?", hint: null },
  { id: 191, text: "What was your first purchase over $1,000?", hint: null },
  { id: 192, text: "How many people do you currently know who are looking for a job?", hint: null },
  { id: 193, text: "Do you have a current resume?", hint: null },
  { id: 194, text: "How many pairs of shoes do you own? Not including athletic shoes.", hint: null },
  { id: 195, text: "Do you like fireworks?", hint: null },
  { id: 196, text: "Which of the following have you done: skydived, bungee jumped, scuba dived, parasailed, or hang glided?", hint: null },
  { id: 197, text: "Which of those did you like best? Any you would not do again?", hint: null },
  { id: 198, text: "Have you ever been in a helicopter?", hint: null },
  { id: 199, text: "Have you ever been on television?", hint: null },
  { id: 200, text: "What books have you read more than once?", hint: null },
  { id: 201, text: "Do you know your blood type?", hint: null },
  { id: 202, text: "Have you ever missed a flight?", hint: null },
  { id: 203, text: "What nicknames have you had in your life?", hint: null },
  { id: 204, text: "Have you ever yelled at a stranger?", hint: null },
  { id: 205, text: "Have you ever been a part of or witnessed road rage?", hint: null },
  { id: 206, text: "Have you ever witnessed a crime? Did you report it?", hint: null },
  { id: 207, text: "Have you ever been in a fight where punches were thrown?", hint: null },
  { id: 208, text: "What city did you live in when you were 5, 19, and 25?", hint: "This one often creates surprising connections between people at the table." },
  { id: 209, text: "Have you ever saved anyone's life?", hint: null },
  { id: 210, text: "What TV character can you most identify with?", hint: null },
  { id: 211, text: "People say — 'you look like ___________.'", hint: null },
  { id: 212, text: "Have you ever been on a blind date?", hint: null },
  { id: 213, text: "Have you ever been bitten by an animal?", hint: null },
  { id: 214, text: "What is the longest you've ever been without going outside?", hint: null },
  { id: 215, text: "What is the longest you have ever gone without going inside?", hint: null },
  { id: 216, text: "Do you own a tent?", hint: null },
  { id: 217, text: "Have you ever built anything significant — physically built?", hint: null },
  { id: 218, text: "How many showers do you take a week?", hint: null },
  { id: 219, text: "If you had to pursue one occupation for 10 years at $50K working 20 hours a week, which would you choose: Auctioneer, Schoolmaster, Stenographer, or Alderman?", hint: null },
  { id: 220, text: "Same deal at $110K for 30 hours a week: Falconer, Beekeeper, Tavern Keeper, or Inn Keeper?", hint: null },
  { id: 221, text: "Same deal at $125K for 40 hours a week: Mason, Warden, Lumberman, or Oxen Driver?", hint: null },
  { id: 222, text: "Same deal at $250K for 50 hours a week with 50% travel: Ship Shanty Leader, Body Preparer for Burial, Balloonist, or Traveling Merchant?", hint: null },
  { id: 223, text: "If your occupation had to be randomly drawn from one of those four groups — which group would you choose?", hint: null },
  { id: 224, text: "What is your greatest athletic feat?", hint: null },
  { id: 225, text: "Why do you live where you live?", hint: null },
  { id: 226, text: "What is the first movie you ever saw in a movie theatre?", hint: null },
  { id: 227, text: "What was your first public speaking experience? How did it go?", hint: null },
  { id: 228, text: "What is the name of your freshman year college roommate? What are they doing today?", hint: null },
  { id: 229, text: "Have you ever fired anyone? Have you ever been fired?", hint: null },
  { id: 230, text: "Have you ever been on TV?", hint: null },
  { id: 231, text: "Have you ever been written about or quoted in the paper?", hint: null },
  { id: 232, text: "In high school, what three adjectives described you? In college? Today?", hint: null },
  { id: 233, text: "Do you have any friends whose occupation is a talent — professional athlete, entertainer, etc.?", hint: null },
  { id: 234, text: "What is your favorite reality TV show? If you had to be on one, which would you choose?", hint: null },
  { id: 235, text: "Who has been the most influential person in your life, ever? Today?", hint: null },
  { id: 236, text: "Can you play a musical instrument?", hint: null },
  { id: 237, text: "Have you ever auditioned for anything?", hint: null },
  { id: 238, text: "Who is your favorite entertainer?", hint: null },
  { id: 239, text: "What is your favorite vegetable?", hint: null },
  { id: 240, text: "What TV programs will you stay home to watch?", hint: null },
  { id: 241, text: "What is your preferred source of news — internet, paper, TV, or radio?", hint: null },
  { id: 242, text: "What is the biggest difference between who you are today and who you were half your years ago?", hint: null },
  { id: 243, text: "What is your greatest fear?", hint: null },
  { id: 244, text: "Have you ever seen a tornado?", hint: null },
  { id: 245, text: "Have you ever been on a private plane?", hint: null },
  { id: 246, text: "What is your favorite movie line?", hint: null },
  { id: 247, text: "How many very close friends do you have?", hint: null },
  { id: 248, text: "What was your best investment? Worst?", hint: null },
  { id: 249, text: "If you could give $1,000,000 to a single charity, which would it be?", hint: null },
  { id: 250, text: "What is your favorite season — spring, summer, winter, or fall?", hint: null },
  { id: 251, text: "What is your favorite holiday?", hint: null },
  { id: 252, text: "How many servings of something sweet — candy, dessert, etc. — do you eat a week?", hint: null },
  { id: 253, text: "How often do you exercise?", hint: null },
  { id: 254, text: "What do you think is the worst invention of the past 25 years? What is the best?", hint: null },
  { id: 255, text: "What is the greatest sporting event you have ever seen live?", hint: null },
  { id: 256, text: "Have you ever had a crush on a teacher or instructor? Did you do anything about it?", hint: null },
  { id: 257, text: "What associations, organizations, and clubs do you belong to?", hint: null },
  { id: 258, text: "Fill in this blank: If I ran for public office, I would have a hard time getting the ___________ vote.", hint: null },
  { id: 259, text: "Is there anyone you almost married?", hint: null },
  { id: 260, text: "Fill in this blank: I have so much of ___________, I won't run out of it for a long, long time.", hint: null },
  { id: 261, text: "Have you ever had a religious experience?", hint: null },
  { id: 262, text: "How many computers are in your home?", hint: null },
  { id: 263, text: "Have you ever seen a streaker? Have you ever been one?", hint: null },
  { id: 264, text: "Have you ever called into work 'sick' when you weren't?", hint: null },
  { id: 265, text: "How much time do you spend each week cooking?", hint: null },
  { id: 266, text: "How many times do you get your car washed a year?", hint: null },
  { id: 267, text: "Do you have any addictions?", hint: null },
  { id: 268, text: "How many hairstyles have you had in your life? How many hair colors?", hint: null },
  { id: 269, text: "How many schools have you attended?", hint: null },
  { id: 270, text: "Have you ever won a contest?", hint: null },
  { id: 271, text: "Have you ever won a raffle or a prize?", hint: null },
  { id: 272, text: "If you had to be a teacher, what subject would you teach to what grade?", hint: null },
  { id: 273, text: "Have you ever helped a stranger for more than a few minutes? If so, with what?", hint: null },
  { id: 274, text: "Would you prefer to live in a place where it is daylight 23 hours a day or only 6 hours a day?", hint: null },
  { id: 275, text: "What is something that is currently legal that you think should be illegal?", hint: null },
  { id: 276, text: "How would you finish this sentence: I was the last one I know to buy/adopt/begin ___________.", hint: null },
  { id: 277, text: "If you had to change your first name to something else, what would it be?", hint: null },
  { id: 278, text: "How many people do you know that have the same first name as you? Do you think they represent your name well?", hint: null },
  { id: 279, text: "What person, place, or thing is at the center of your life?", hint: null },
  { id: 280, text: "Do you know how much money is in your wallet right now?", hint: null },
  { id: 281, text: "Is there a place or time when you do your best thinking?", hint: null },
  { id: 282, text: "Is there any profession that you wish required wearing a uniform so you'd know who they were?", hint: null },
  { id: 283, text: "What physical attribute do you like most about yourself? Least?", hint: null },
  { id: 284, text: "Do you have any superstitions?", hint: null },
  { id: 285, text: "Is there any day of the year that you do something special — a celebration or tradition that isn't a holiday or birthday?", hint: null },
  { id: 286, text: "Where and when do you most often daydream?", hint: null },
  { id: 287, text: "Finish this sentence: There are very few people who are better than me at ___________.", hint: null },
  { id: 288, text: "Have you ever quit anything significant?", hint: null },
  { id: 289, text: "Finish this sentence: Sundays are for ___________.", hint: null },
  { id: 290, text: "Is there any rule in professional sports that you are against?", hint: null },
  { id: 291, text: "If money and time were no object, how many children would you have?", hint: null },
  { id: 292, text: "Why did your parents name you the name you have?", hint: null },
  { id: 293, text: "What is your family heritage?", hint: null },
  { id: 294, text: "What is more important to you — landscaping or furniture?", hint: null },
  { id: 295, text: "Do you have a favorite room in the house?", hint: null },
  { id: 296, text: "Have you ever been asked to leave a public place? Why?", hint: null },
  { id: 297, text: "If a major network offered to follow you around for 30 days to make a movie about your life, would you let them?", hint: "Assume you'd have full privacy. If not for free, how much would they have to pay you?" },
  { id: 298, text: "Do you know anyone who has either gained or lost half or more of their adult body weight?", hint: null },
  { id: 299, text: "How much would you be willing to pay per inch to be taller? How much per pound to be lighter — and the weight would stay off?", hint: null },
  { id: 300, text: "Do you have any advice for anyone famous?", hint: null },
  { id: 301, text: "Which would you rather do for four hours — clean your house or do yard work?", hint: null },
  { id: 302, text: "What is the weirdest tradition or habit of your significant other?", hint: null },
  { id: 303, text: "If tomorrow morning you could wake up fluent in 4 additional languages or proficient in 4 additional instruments — which would you choose?", hint: null },
  { id: 304, text: "What languages or instruments would they be?", hint: null },
  { id: 305, text: "What was the last big fight you had (with anyone)?", hint: null },
  { id: 306, text: "If you could have an amazing singing voice or be amazing at an instrument, which would you choose?", hint: null },
  { id: 307, text: "Where is your favorite place to shop?", hint: null },
  { id: 308, text: "What is the scariest, most daring thing you've ever done?", hint: null },
  { id: 309, text: "I just gave you $500. Would you rather spend it in a clothing store, a hardware store, or a grocery store?", hint: null },
  { id: 310, text: "If you could permanently add one person to your extended family, who would it be?", hint: null },
  { id: 311, text: "What's your favorite TV show of all time?", hint: null },
  { id: 312, text: "What's the dumbest thing you've ever done?", hint: null },
  { id: 313, text: "Give a one-minute argument for one of your biggest pet peeves.", hint: null },
  { id: 314, text: "To what brand are you stupidly loyal?", hint: null },
  { id: 315, text: "How many different jobs have you held in your life?", hint: null },
  { id: 316, text: "No one else is around. What do you gorge on?", hint: null },
  { id: 317, text: "How many different addresses have you had in your life?", hint: null },
  { id: 318, text: "What is (to you) your most appealing physical attribute?", hint: null },
  { id: 319, text: "What percentage of all the clothes you own have you not worn in the past 12 months?", hint: null },
  { id: 320, text: "Wave a magic wand and move this gathering to anyplace in the world where you have been. Where are we now?", hint: null },
  { id: 321, text: "Who (that you know) seems to live the most idyllic life imaginable?", hint: null },
  { id: 322, text: "If money is not an object: where do you want to retire?", hint: null },
  { id: 323, text: "If you could be the personal assistant of anyone in the world, who would it be?", hint: null },
  { id: 324, text: "What's the worst job you've ever held?", hint: null },
  { id: 325, text: "What are your THREE most prized possessions?", hint: null },
  { id: 326, text: "How many times in your life have you lost your wallet, keys, or phone and never found them?", hint: null },
  { id: 327, text: "How would you design a spice rack for a blind person?", hint: null },
  { id: 328, text: "What is your favorite religious song?", hint: null },
  { id: 329, text: "What do you think happens to a person after they die?", hint: null },
  { id: 330, text: "You just got kicked out of the United States. Where would you go?", hint: null },
  { id: 331, text: "What is the longest grudge you've ever held? Over what?", hint: null },
  { id: 332, text: "With whom do you speak on the phone the most (other than your significant other)?", hint: null },
  { id: 333, text: "You can only have one meal for every meal for one month. What is it?", hint: null },
  { id: 334, text: "What is your least favorite personal hygiene task?", hint: null },
  { id: 335, text: "One piece of clothing that you once owned and you'd like to have back?", hint: null },
  { id: 336, text: "Rattle off something long-ish that you have memorized.", hint: null },
  { id: 337, text: "Have you read a book that you feel changed your life?", hint: null },
  { id: 338, text: "Who was your favorite teacher in high school?", hint: null },
  { id: 339, text: "For what reason were you most often punished or grounded?", hint: null },
  { id: 340, text: "What is your favorite thing to do for another person?", hint: null },
  { id: 341, text: "What is the luckiest break you've ever received in your career?", hint: null },
  { id: 342, text: "What is the most generous act of kindness anyone has ever done for you?", hint: null },
  { id: 343, text: "What's the family tradition that you will NEVER give up?", hint: null },
  { id: 344, text: "What's the family tradition that you will NEVER maintain?", hint: null },
  { id: 345, text: "Choose one dinner: Dinner at The Vatican, Buckingham Palace, or The White House?", hint: "Current or previous occupant of your choosing." },
  { id: 346, text: "On a scale of 1 to 10, how difficult would it be for you to change a tire? (1 = easy)", hint: null },
  { id: 347, text: "Who is your favorite pet of all time?", hint: null },
  { id: 348, text: "If someone wrote a biography about you, what do you think the title should be?", hint: null },
  { id: 349, text: "Have you ever saved anyone's life... or come close?", hint: null },
  { id: 350, text: "You can have one hour each with FIVE people who are now dead. Who are they?", hint: "People you knew or didn't know — either one." },
  { id: 351, text: "Do you own: a garlic press? A watch worth more than $1,000? A tire pressure gauge?", hint: null },
  { id: 352, text: "How many professional sporting events do you attend in an average year?", hint: null },
  { id: 353, text: "What's the first movie you ever remember seeing in a theater?", hint: null },
  { id: 354, text: "Who is the most famous person you have ever met?", hint: null },
  { id: 355, text: "What is the biggest difference between you now and you when you were half your current age?", hint: null },
  { id: 356, text: "What one song would you love to have played at your funeral... but probably won't?", hint: null },
  { id: 357, text: "What is the one food item you try really hard not to run out of at home?", hint: null },
  { id: 358, text: "Approximately how many people do you know with your last name?", hint: null },
  { id: 359, text: "Finish this sentence: I might just be the smartest person in the room when it comes to:", hint: null },
  { id: 360, text: "What jobs have you quit?", hint: null },
  { id: 361, text: "What place or location do you literally dream of most often?", hint: null },
  { id: 362, text: "Pick one: Do you prefer getting up early or staying up late?", hint: null },
  { id: 363, text: "You now have to drive one of the previous cars you've owned. Which is it?", hint: null },
  { id: 364, text: "Name a friend with whom you've lost touch — and you'd like to reunite.", hint: null },
  { id: 365, text: "Do you think a hotdog is a sandwich?", hint: null },
  { id: 366, text: "What is your favorite thing to do on a Sunday afternoon?", hint: null },
  { id: 367, text: "Have you ever been kicked out of a bar or restaurant?", hint: null },
  { id: 368, text: "Name two drinks that at one time were your favorite. And what is it now?", hint: null },
  { id: 369, text: "If someone from St. Louis asks you 'Where did you go to school?' and you were homeschooled, should you give your parent's home address?", hint: null },
  { id: 370, text: "Do you have an all-time favorite actor? Performer?", hint: null },
  { id: 371, text: "Have you ever written to the newspaper? Was it published?", hint: null },
  { id: 372, text: "Have you ever had a terrible roommate?", hint: null },
  { id: 373, text: "If you had to give up listening to music or reading (including books on tape) for a year — which?", hint: null },
  { id: 374, text: "Have you spoken at a funeral?", hint: null },
  { id: 375, text: "Do you know the color of your master bathroom wall?", hint: null },
];

// ── BONUS QUESTIONS ───────────────────────────────────────────────────────────
export const BONUS_QUESTIONS = [
  { id: "b1", text: "What is something you believed with total certainty as a child that turned out to be completely wrong?", hint: null, type: "bonus" },
  { id: "b2", text: "If you could have dinner with any three people — living or dead — who aren't famous, who would they be?", hint: "The 'no famous people' rule makes this one interesting.", type: "bonus" },
  { id: "b3", text: "What is the most spontaneous thing you have ever done?", hint: null, type: "bonus" },
  { id: "b4", text: "Finish this sentence: The older I get, the more I appreciate ___________.", hint: null, type: "bonus" },
  { id: "b5", text: "What is one thing you do differently than almost everyone you know?", hint: null, type: "bonus" },
  { id: "b6", text: "If your life had a theme song — the one that plays when you walk into a room — what would it be?", hint: null, type: "bonus" },
  { id: "b7", text: "What is the most embarrassing thing that has ever happened to you in public?", hint: null, type: "bonus" },
  { id: "b8", text: "What is something you have never told your parents but wish you could?", hint: "If your parents are present, feel free to skip this one.", type: "bonus" },
  { id: "b9", text: "Would you rather know the date of your death, or the cause?", hint: null, type: "bonus" },
  { id: "b10", text: "What job would you be terrible at, even with years of training?", hint: null, type: "bonus" },
  { id: "b11", text: "Finish this sentence: The one thing I will never understand about people is ___________.", hint: null, type: "bonus" },
  { id: "b12", text: "What is the nicest thing a stranger has ever done for you?", hint: null, type: "bonus" },
  { id: "b13", text: "If you could go back and relive one ordinary day — nothing special, just a regular day — which would it be and why?", hint: null, type: "bonus" },
  { id: "b14", text: "What habit did you pick up from your parents that you swore you never would?", hint: null, type: "bonus" },
  { id: "b15", text: "What is something you are surprisingly bad at given how long you've been doing it?", hint: null, type: "bonus" },
  { id: "b16", text: "If you had to eat at the same restaurant every week for a year, which would it be?", hint: null, type: "bonus" },
  { id: "b17", text: "What is the most useful thing you know how to do that most people don't?", hint: null, type: "bonus" },
  { id: "b18", text: "Finish this sentence: The version of me from ten years ago would be surprised that I now ___________.", hint: null, type: "bonus" },
  { id: "b19", text: "What would you do with a completely free, unscheduled Saturday — no obligations, no one else's needs?", hint: null, type: "bonus" },
  { id: "b20", text: "What is something you have strong opinions about that most people don't care about at all?", hint: null, type: "bonus" },
  { id: "b21", text: "If you had to describe your childhood in three words, what would they be?", hint: null, type: "bonus" },
  { id: "b22", text: "What is the worst advice you have ever followed?", hint: null, type: "bonus" },
  { id: "b23", text: "What is something you own that has no practical value but that you would never get rid of?", hint: null, type: "bonus" },
  { id: "b24", text: "Would you rather be known as the funniest person in the room, or the smartest?", hint: null, type: "bonus" },
  { id: "b25", text: "What is the most trouble you ever got into that your parents never found out about?", hint: null, type: "bonus" },
];

export const DEFAULT_ABOUT = `These questions were written starting in 1997 by someone who got tired of small talk at dinner parties — the endless "where do you live, what do you do" loop that always ended in uncomfortable silence.

The idea is simple: get to know the person, not their résumé. Find out what they feel, think, believe — and why.

Two rules:

Be sincere. Treat this as a real conversation, not a game show. You may be entertained, but don't miss out on a lifelong connection.

Be impartial. Your job is to learn about the other person, not to judge their answers. Whatever the answer to whatever the question — it isn't a wrong answer. The antidote to judgment? Curiosity.

Hit Skip if a question feels wrong for the moment — no explanation needed. Rate questions to surface the best ones over time.`;

export const DEFAULT_INSTRUCTIONS = `How to Play

The Questioner reads the question aloud to the group. One person is selected to answer — that person becomes the next Questioner.

Multiplayer Mode (2–15 players)
Everyone joins with their name. The app randomly selects who answers each round, making sure everyone gets a turn before anyone goes twice. The person who answers becomes the Questioner for the next round.

Solo Mode
Just you and the questions. Use it to browse, reflect, or prep great conversation starters before your next gathering. Hit Next to move through questions at your own pace.

A few tips from the creator:
— Make it light-hearted. You don't have to present this as a "game." Just say: "I heard a weird question the other day — curious how you'd answer it."
— Don't rush. The questions are just conversation starters, not a quiz.
— Skip freely. If a question feels wrong for the room, skip it. No explanation needed.
— Be impartial. Don't react to answers — be curious about them instead.
— The best questions often lead somewhere unexpected. Follow the conversation, not the app.`;
